#!/usr/bin/env ruby

require 'bundler/setup'
require 'google/agenda/ade/sync'
require 'commander/import'

program :name, 'ade-ga-sync'
program :version, Google::Agenda::Ade::Sync::VERSION
program :description, 'Google Agenda ADE synchronization script'
program :help, 'Author', 'Vincent Tavernier <vincent.tavernier@ensimag.grenoble-inp.fr>'

# Run default script

default_command :sync
command :sync do |c|
  c.option '-n', '--dry-run', 'Do not update target Google Agenda'
  c.option '-c', '--config', String, "Path to config file. Defaults to #{Google::Agenda::Ade::Sync::CONFIGURATION_FILE}"
  c.option '-k', '--credentials', String, "Path to the API credentials file. Defaults to #{Google::Agenda::Ade::Sync::CREDENTIALS_FILE}"
  c.option '-s', '--secrets', String, "Path to the Oauth2 secrets storage file. Defaults to #{Google::Agenda::Ade::Sync::SECRETS_STORE_FILE}"
  c.option '--skip-verify', "Skip SSL certificate verification."
  c.action do |args, options|
    # Setup defaults
    options.default :dry_run => false,
                    :config => Google::Agenda::Ade::Sync::CONFIGURATION_FILE,
                    :credentials => Google::Agenda::Ade::Sync::CREDENTIALS_FILE,
                    :secrets => Google::Agenda::Ade::Sync::SECRETS_STORE_FILE,
                    :skip_verify => false

    # Setup OpenSSL verify
    if options.skip_verify
      # http://stackoverflow.com/a/1113614
      OpenSSL::SSL.const_set(:VERIFY_PEER, OpenSSL::SSL::VERIFY_NONE)
    end

    # Start entry point
    Google::Agenda::Ade::Sync::EntryPoint.run(options.dry_run,
                                              options.config,
                                              options.credentials,
                                              options.secrets)
  end
end
